name 'bitlancer-cloudfuse'
version '0.0.1'
source 'git://github.com/Bitlancer/puppet-cloudfuse.git'
author 'bitlancer'
license 'Apache 2.0'
summary 'Puppet module for Cloudfuse'
description 'Module for Cloudfuse'
project_page 'https://github.com/Bitlancer/puppet-cloudfuse'
dependency 'puppetlabs/stdlib', '>= 2.4.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
